### PR TITLE
Index serialization

### PR DESCRIPTION
**Pull request by vladimiry**
The version in package.json has not been updated.

### CODE REVIEW

**Comment by vladimiry** [comment]
I decided I better don't add runtime dependencies, like `msgpack-lite` module. So serialize/deserialize functions need to be provided by library consumer. The code example in readme and serialization.spec.ts use serialize/deserialize functions based on `msgpack-lite`.

**Comment by localvoid** [comment]
Thanks.

Before publishing to npm I would like to reorganize project:

- Move everything into a separate github organization
- Split into different packages:
  - `ndx` - data structures
  - `ndx-index` - indexing function
  - `ndx-query` - basic query function (it is possible to create a more advanced query functions)
  - `ndx-serialize-msgpack` - serialization
  - `ndx-compat` - backward compatible API

**Comment by vladimiry** [comment]
@localvoid sounds great, can you also consider adding a method to `DocumentIndex` like the following?
```typescript
indexed(documentId: I): boolean {
  return this._documents.has(documentId);
}
```

**Comment by vladimiry** [comment]
> Before publishing to npm I would like to reorganize project:

Just a note, it also might look like a monorepo project (like packages folders for individual projects, Lerna tool, etc).

**Comment by localvoid** [comment]
Yes, I am using Lerna for several projects. I think that with `ndx` it would be quite easy to stabilize core data structures and let them live in a separate repo, also there won't be any problems with Jest+multi-project code coverage.

**Pull request merged**
